import { Inter } from 'next/font/google'
import './globals.css'
import { Box, Toolbar, Typography } from '@mui/material'
import NavBar from '@/components/shared/NavBar'
import Footer from '@/components/shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box>
          <NavBar></NavBar>
        </Box>
        <Toolbar />
        <Box component="main" sx={{ margin: "auto", minHeight: "100vh" }}>
          {children}
        </Box>
        <Box component="footer" >
          <Footer></Footer>
        </Box>

      </body>
    </html>
  )
}
