import { Inter } from 'next/font/google'
import './globals.css'
import { Box, Toolbar, Typography } from '@mui/material'
import NavBar from '@/components/shared/NavBar'
import Footer from '@/components/shared/Footer'
import NoSsr from '@/components/NoSsrc/NoSsr'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Asif Ahammad Profile',
  description: 'I am Asif Ahammad A Dedicated Web Developer. As Junior Web Developer I want to learn Many things. Generated by  next.js ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <title>Home</title>
        </Head>
        <Box>
          <AuthProvider>
            <NavBar></NavBar>
          </AuthProvider>
        </Box>
        <Toolbar />
        <Box component="main" sx={{ margin: "auto", minHeight: "100vh" }}  >
          {children}
        </Box>
        <Box component="footer" >
          <Footer></Footer>
        </Box>

      </body>
    </html>
  )
}
